# Generated by Django 2.0.5 on 2018-05-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='from_date_conf',
            field=models.CharField(max_length=50, null=True, verbose_name='from'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='from_date_industrial',
            field=models.CharField(max_length=50, null=True, verbose_name='from date'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='from_date_teaching',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='to_date_conf',
            field=models.CharField(max_length=50, null=True, verbose_name='to'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='to_date_industrial',
            field=models.CharField(max_length=50, null=True, verbose_name='to date'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='to_date_teaching',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='total_duration_conf',
            field=models.CharField(max_length=50, null=True, verbose_name='total duration'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='total_duration_teaching',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='university_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Sslc',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='from_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='to_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='total_duration',
            field=models.CharField(max_length=50),
        ),
    ]
