# Generated by Django 2.0.5 on 2018-06-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='family_members',
            field=models.IntegerField(default=0),
        ),
    ]
