# Generated by Django 2.0.5 on 2018-06-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180602_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profbody',
        ),
        migrations.RemoveField(
            model_name='user',
            name='proficiency_english',
        ),
        migrations.RemoveField(
            model_name='user',
            name='proficiency_hindi',
        ),
        migrations.RemoveField(
            model_name='user',
            name='proficiency_kannada',
        ),
        migrations.AddField(
            model_name='user',
            name='english_speak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hindi_speak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='kannada_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='kannada_speak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='kannada_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Amount',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Bank',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Branch',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Date',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='neft',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NEFT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='no_member',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reservation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uti',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='UTI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_selection',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='year selection'),
        ),
    ]
