# Generated by Django 2.0.5 on 2018-05-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180529_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='Affiliation',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Awards',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='BE',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='BankDetails',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Bsc',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Conference',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='English',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Hindi',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='IndustrialExperience',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Kannada',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='MTech',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='MphilMca',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='OtherCourse',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='PHD',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Referral',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Research',
        ),
        migrations.AddField(
            model_name='faculty',
            name='Amount',
            field=models.CharField(default='0', max_length=35, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Bank',
            field=models.CharField(default='NA', max_length=35, verbose_name='Bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Branch',
            field=models.CharField(default='NA', max_length=35, verbose_name='Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Class_Awarded_be',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Class_Awarded_bsc',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Class_Awarded_mca',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Class_Awarded_mtech',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Class_Awarded_other',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Class_Awarded_phd',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Course_be',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Course_bsc',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Course_mca',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Course_mtech',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Course_other',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Course_phd',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Date',
            field=models.CharField(default='NA', max_length=35, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Institution_Name_be',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Institution_Name_bsc',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Institution_Name_mca',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Institution_Name_mtech',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Institution_Name_other',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Institution_Name_phd',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Name_university',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Passing_Year_be',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Passing_Year_bsc',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Passing_Year_mca',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Passing_Year_mtech',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Passing_Year_other',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Passing_Year_phd',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Percent_Marks_be',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Percent_Marks_bsc',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Percent_Marks_mca',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Percent_Marks_mtech',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Percent_Marks_other',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Percent_Marks_phd',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Spec_awards_particulars',
            field=models.CharField(default='NA', max_length=50, verbose_name='Particulars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Specialisation_be',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Specialisation_bsc',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Specialisation_mca',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Specialisation_mtech',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Specialisation_other',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='Specialisation_phd',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='area_reasearch',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='conf_International',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='conf_conducted_org',
            field=models.CharField(default='NA', max_length=50, verbose_name='organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='contact_no',
            field=models.CharField(default='NA', max_length=50, verbose_name='contact no'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='designation',
            field=models.CharField(default='NA', max_length=50, verbose_name='designationsi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='experience_years',
            field=models.CharField(default='NA', max_length=50, verbose_name='experience years'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='from_date',
            field=models.CharField(default='NA', max_length=50, verbose_name='from date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='grade',
            field=models.CharField(default='NA', max_length=50, verbose_name='grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='international',
            field=models.CharField(default='NA', max_length=50, verbose_name='International'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='national',
            field=models.CharField(default='NA', max_length=50, verbose_name='National'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='neft',
            field=models.CharField(default='NA', max_length=50, verbose_name='NEFT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='no_member',
            field=models.CharField(default='NA', max_length=50, verbose_name='members'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='organisation',
            field=models.CharField(default='NA', max_length=50, verbose_name='organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='position_held',
            field=models.CharField(default='NA', max_length=50, verbose_name='position held'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='profbody',
            field=models.CharField(default='NA', max_length=50, verbose_name='body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='proficiency_english',
            field=models.CharField(default='NA', max_length=50, verbose_name='proficiency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='proficiency_hindi',
            field=models.CharField(default='NA', max_length=50, verbose_name='proficiency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='proficiency_kannada',
            field=models.CharField(default='NA', max_length=50, verbose_name='proficiency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='state',
            field=models.CharField(default='NA', max_length=50, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='title_paper',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='to_date',
            field=models.CharField(default='NA', max_length=50, verbose_name='to date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='total_duration',
            field=models.CharField(default='NA', max_length=50, verbose_name='total duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='total_experience',
            field=models.CharField(default='NA', max_length=50, verbose_name='experience'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='total_internationalConf',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='total_researchExp',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.CharField(default='NA', max_length=50, verbose_name='university'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='uti',
            field=models.CharField(default='NA', max_length=35, verbose_name='UTI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='year_month_pub',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='year_selection',
            field=models.CharField(default='NA', max_length=50, verbose_name='year selection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_birth',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='position',
            field=models.CharField(max_length=50, verbose_name='position'),
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
        migrations.DeleteModel(
            name='BankDetails',
        ),
        migrations.DeleteModel(
            name='BE',
        ),
        migrations.DeleteModel(
            name='Bsc',
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
        migrations.DeleteModel(
            name='IndustrialExperience',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.DeleteModel(
            name='MphilMca',
        ),
        migrations.DeleteModel(
            name='MTech',
        ),
        migrations.DeleteModel(
            name='OtherCourse',
        ),
        migrations.DeleteModel(
            name='PHD',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='Research',
        ),
    ]
