# Generated by Django 2.0.5 on 2018-06-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180603_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ifsc',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='IFSC'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Amount',
            field=models.CharField(blank=True, default='500', max_length=35, null=True, verbose_name='Amount'),
        ),
    ]
