# Generated by Django 2.0.5 on 2018-06-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180602_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='english_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='english_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hindi_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hindi_write',
            field=models.BooleanField(default=False),
        ),
    ]
