# Generated by Django 2.0.5 on 2018-06-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180602_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
    ]
