# Generated by Django 2.0.5 on 2018-06-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180603_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uti',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='UTR'),
        ),
    ]
