# Generated by Django 2.0.5 on 2018-06-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180602_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
