# Generated by Django 2.0.5 on 2018-06-04 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_declaration_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
