# Generated by Django 2.0.5 on 2018-06-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180604_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Passing_Year',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='Percent_or_grade',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='maximum_marks_or_grade',
            field=models.CharField(max_length=5),
        ),
    ]
